### ISSUE TITLE
Can't open preview

### ISSUE THREAD

**Issue by Bebotron** [ajshort/vscode-latex-preview#17]
When I try to preview a file I get the error:
Unable to open 'Preview "filename.tex"': Cannot read property 'map' of undefined.

Windows 10
v.1.15.1

**Comment by ajshort** [comment]
Are you using latexmk? If so, do you have Perl installed?

**Comment by Bebotron** [comment]
No I’m using pdflatex

**Comment by btracey** [comment]
I have the same issue. OSX 10.12.6 . Latex preview 0.5.1, latex workshop 3.5.3. I haven't changed any of the default settings. The same issue happens if I switch "latex-preview.command" to latexmk (and I do have perl installed).

**Comment by btracey** [comment]
I realized that clicking the "view PDF file in new tab" does work (and updates properly on save), it's just the "Open Preview" button that gives the error.

**Comment by LLJJDD** [comment]
I've got the same problem.
Unable to open 'Preview "filename.tex"': Cannot read property 'map' of undefined.
Using the default settings, with perl, Tex Live, Latex Workshop installed.
Win10.

**Comment by joshuagruenstein** [comment]
Same problem on Mac OS 10.13.1.

**Comment by LucasAmos** [comment]
same problem macos 10.13.2, visual studio code, latex workshop and latex preview

**Comment by Jue-Xu** [comment]
Same problems on macos 10.13.2

**Comment by xindiguo** [comment]
Same problem on mac os 10.12.6

**Comment by Nexolight** [comment]
Windows 10, Pearl, TeX Live and LaTeX workshop installed - Same Problem. Also the "View LaTeX PDF File in new tab" Does not work for me. Apart from the "Cannot read property 'map' of undefined" error when clicking "Open Preview"

Edit: The same happens for both on Void Linux with TeX Live.

**Comment by gurkang** [comment]
Same problem on mac os 10.11.6

**Comment by johndebord** [comment]
Any update?

**Comment by ajshort** [comment]
Unfortunately I'm unable to replicate this issue. If someone has a basic example project they can zip up and attach to the issue it would be appreciated.

Or if someone can run the extension under the vscode extension debugger and capture a stack trace that would be even better. All you need to do is clone the extension repository, open the folder in vscode and run the project using F5.

**Comment by Falthazar** [comment]
Same issue. Just downloaded this .tex: http://tnerual.eriogerg.free.fr/vimqrc.tex

Tried to preview it but got the same error. This is on Windows 7.

**Comment by C1710** [comment]
@ajshort I just tried running it using the extension debugger, but it returns another error (in German):

```
C:\Program Files\Microsoft VS Code\Code.exe --debugBrkPluginHost=47755 --debugId=1da735a0-a508-4f76-a037-d4efca185c26 --extensionDevelopmentPath=C:\Users\const\git\vscode-latex-preview 
Fehler beim Aktivieren der Erweiterung "ajshort.latex-preview": Cannot find module 'C:\Users\const\git\vscode-latex-preview\out\src\extension'.
extensionHostProcess.js:673
Activating extension `ajshort.latex-preview` failed:  Cannot find module 'C:\Users\const\git\vscode-latex-preview\out\src\extension'
extensionHostProcess.js:418
Here is the error stack:  Error: Cannot find module 'C:\Users\const\git\vscode-latex-preview\out\src\extension'
extensionHostProcess.js:418
	at Function.Module._resolveFilename (module.js:470:15)
	at Function.Module._load (module.js:418:25)
	at Function.J.Z.t.getExtensionPathIndex.then.o._load (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:653:398)
```

**BUT** somehow it works when using it while I have the folder opened when I try to open the preview.  
Since I don't know anything about VS code - I actually just looked for a Hi-DPI alternative to running [gummi](https://github.com/alexandervdm/gummi) inside WSL using an X-server 😅 - I don't know how to provide more information on this topic, sorry 😕 
(This is on Windows, obviously)

**Comment by eisenwinter** [comment]
can confirm @C1710 ,  this issue only appears when you open the file directly, it wont once you open the folder (File -> Open Folder), select the tex file - everything works. if you open the file directly without the folder it will throw the mentioned error

**Comment by mlouielu** [comment]
Can confirmed @eisenwinter at vscode 1.21.0, using open folder and the issue didn't come up again.

**Comment by reisdev** [comment]
@eisenwinter , you're right. Opening the complete folder instead of just the .tex file solved the problem. I guess that's because it uses others files that are created with the .tex file.

**Comment by qingdujun** [comment]
**ERROR:** command 'vscode.previewHtml' not found. 

Now, `vscode.previewHtml` has been removed? You also can see https://github.com/Microsoft/vscode-cosmosdb/issues/1070 .

**Comment by jmussman** [comment]
More to the point vscode.previewHtml was replaced by the webview api: https://github.com/Microsoft/vscode/issues/62630. All the sudden, latex preview has stopped working because I think it finally disappeared in the current update to vscode?
